//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamTemp.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamTemp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I created this application while I was in isolation because Covid19-positive. I fully acknowledge the full fullness of uselessness of this project, I did it just to try out some Xamarin features at evenings. If you would like to let me know your opinion, write me at daniele.tentoni.1996@gmail.com or open an issue on Github..
        /// </summary>
        public static string AboutBody {
            get {
                return ResourceManager.GetString("AboutBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Xam Temperature! Use this application to store your measurements of body temperature and blood oxygen saturation before communicate them to your doctor. Swipe from left to right to mark a report as communicated or from right to left to delete it..
        /// </summary>
        public static string AboutIntro {
            get {
                return ResourceManager.GetString("AboutIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad....
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this report? (You will not be able to retreive it).
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown adding a report: {0}.
        /// </summary>
        public static string ExceptionMessageReportAdd {
            get {
                return ResourceManager.GetString("ExceptionMessageReportAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown deleting a report: {0}.
        /// </summary>
        public static string ExceptionMessageReportDelete {
            get {
                return ResourceManager.GetString("ExceptionMessageReportDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown resetting data: {e.Message}.
        /// </summary>
        public static string ExceptionMessageReportReset {
            get {
                return ResourceManager.GetString("ExceptionMessageReportReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception thrown sending a report: {0}.
        /// </summary>
        public static string ExceptionMessageReportSend {
            get {
                return ResourceManager.GetString("ExceptionMessageReportSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback for XamTemp.
        /// </summary>
        public static string FeedbackFor {
            get {
                return ResourceManager.GetString("FeedbackFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input saturation.
        /// </summary>
        public static string InputSaturation {
            get {
                return ResourceManager.GetString("InputSaturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input temperature.
        /// </summary>
        public static string InputTemperature {
            get {
                return ResourceManager.GetString("InputTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, don&apos;t do it..
        /// </summary>
        public static string NotSure {
            get {
                return ResourceManager.GetString("NotSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should send this report to your doctor..
        /// </summary>
        public static string ReportToSend {
            get {
                return ResourceManager.GetString("ReportToSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to reset all report data and restore the initial setup of the applicazion?.
        /// </summary>
        public static string ResetConfirmationMessage {
            get {
                return ResourceManager.GetString("ResetConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, don&apos;t reset..
        /// </summary>
        public static string ResetNo {
            get {
                return ResourceManager.GetString("ResetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, reset data!.
        /// </summary>
        public static string ResetYes {
            get {
                return ResourceManager.GetString("ResetYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        public static string Saturation {
            get {
                return ResourceManager.GetString("Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I&apos;m sure!.
        /// </summary>
        public static string Sure {
            get {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device doesn&apos;t support email sending..
        /// </summary>
        public static string UnsupportedEmail {
            get {
                return ResourceManager.GetString("UnsupportedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported feature.
        /// </summary>
        public static string UnsupportedFeature {
            get {
                return ResourceManager.GetString("UnsupportedFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
